# Page settings
baseurl = "localhost:1313"
title = "Afrique Nature"
languageCode = "en-us"
theme = "custom-elate"

[params]

  custom_css = []

  # Meta
  author = "Louis Hache"
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "afrique nature"
    home = "nav.home"
    work = "nav.work"
    testimonials = "nav.testimonials"
    services = "nav.services"
    gallery = "nav.gallery"
    about = "nav.about"
    contact = "nav.contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "afrique nature"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
    enable = true

  [[params.intro.item]]
    title = "intro.circuit1.title"
    description = "intro.circuit1.description"
    url = "/tours/8days"
    button = "Read more"
    icon = "icon-map"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "intro.circuit2.title"
    description = "intro.circuit2.description"
    url = "/tours/8days"
    button = "Read more"
    icon = "icon-map"
    img = "img_7.jpg"


  [[params.intro.item]]
    title = "intro.circuit3.title"
    description = "intro.circuit3.description"
    url = "/tours/8days"
    button = "Read more"
    icon = "icon-map"
    img = "img_7.jpg"


  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "work.title"
    description = "work.description"
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "work.item1.title"
      subtitle = "work.item1.description"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "work.item2.title"
      subtitle = "work.item2.description"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "work.item3.title"
      subtitle = "work.item3.description"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "work.item4.title"
      subtitle = "work.item4.description"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "work.item5.title"
      subtitle = "work.item5.description"

      [[params.work.row]]
        img = "work_4.jpg"
        alt = "Image4"
        title = "work.item6.title"
        subtitle = "work.item6.description"
  # Work section
  [params.gallery]
    enable = true
    title = "gallery.title"
    description = "gallery.description"

    [[params.gallery.row]]
      img = "gallery_1.jpeg"
      alt = "Image2"
    [[params.gallery.row]]
      img = "gallery_2.jpeg"
      alt = "Image2"
    [[params.gallery.row]]
      img = "gallery_3.jpeg"
      alt = "Image3"
    [[params.gallery.row]]
      img = "gallery_6.jpeg"
      alt = "Image6"
    [[params.gallery.row]]
      img = "gallery_7.jpeg"
      alt = "Image7"
    [[params.gallery.row]]
      img = "gallery_8.jpeg"
      alt = "Image8"
    [[params.gallery.row]]
      img = "gallery_9.jpeg"
      alt = "Image9"
    [[params.gallery.row]]
      img = "gallery_10.jpeg"
      alt = "Image10"
    [[params.gallery.row]]
      img = "gallery_11.jpeg"
      alt = "Image11"
    [[params.gallery.row]]
      img = "gallery_12.jpeg"
      alt = "Image12"
    [[params.gallery.row]]
      img = "gallery_13.jpeg"
      alt = "Image13"
    [[params.gallery.row]]
      img = "gallery_17.jpeg"
      alt = "Image14"
    [[params.gallery.row]]
      img = "gallery_15.jpeg"
      alt = "Image15"
    [[params.gallery.row]]
      img = "gallery_16.jpeg"
      alt = "Image16"
    [[params.gallery.row]]
      img = "gallery_14.jpeg"
      alt = "Image17"
    [[params.gallery.row]]
      img = "gallery_18.jpeg"
      alt = "Image18"
    [[params.gallery.row]]
      img = "gallery_20.jpeg"
      alt = "Image20"
    [[params.gallery.row]]
      img = "gallery_22.jpeg"
      alt = "Image22"
    [[params.gallery.row]]
      img = "gallery_21.jpeg"
      alt = "Image21"
    [[params.gallery.row]]
      img = "gallery_24.jpeg"
      alt = "Image24"
    [[params.gallery.row]]
      img = "gallery_25.jpeg"
      alt = "Image25"
    [[params.gallery.row]]
      img = "gallery_19.jpeg"
      alt = "Image19"
    [[params.gallery.row]]
      img = "gallery_5.jpeg"
      alt = "Image5"
    [[params.gallery.row]]
      img = "gallery_26.jpeg"
      alt = "Image26"
    [[params.gallery.row]]
      img = "gallery_27.jpeg"
      alt = "Image27"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "testimonials.title"
    description = "testimonials.description"

    [[params.testimonials.item]]
      quote = "testimonials.item1.quote"
      person = 'Louis H.'
      # img = "person1.jpg"
      # alt = "Person1"

    # [[params.testimonials.item]]
    #   quote = "testimonials.item2.quote"
    #   person = 'Louis H.'
    #   # img = "person2.jpg"
    #   # alt = "Person2"

    # [[params.testimonials.item]]
    #   quote = "testimonials.item3.quote"
    #   person = 'Louis H.'
    #   # img = "person3.jpg"
    #   # alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "services.title"
    description = "services.description"

    [[params.services.item]]
      title = "services.item1.title"
      description = "services.item1.description"
      icon = "icon-magic-wand"
    [[params.services.item]]
      title = "services.item2.title"
      description = "services.item2.description"
      icon = "icon-bed"
    [[params.services.item]]
      title = "services.item3.title"
      description = "services.item3.description"
      icon = "icon-fire"
    [[params.services.item]]
      title = "services.item4.title"
      description = "services.item4.description"
      icon = "icon-eye"
    [[params.services.item]]
      title = "services.item5.title"
      description = "services.item5.description"
      icon = "icon-video2"
    [[params.services.item]]
      title = "services.item6.title"
      description = "services.item6.description"
      icon = "icon-like"


  # Services section
  [params.passion]
    enable = true
    title = "passion.title"
    description = "passion.description"

    [[params.passion.item]]
      title = "passion.item1.title"
      description = "passion.item1.description"
      icon = "icon-camera"
    [[params.passion.item]]
      title = "passion.item2.title"
      description = "passion.item2.description"
      icon = "icon-star"
    [[params.passion.item]]
      title = "passion.item3.title"
      description = "passion.item3.description"
      icon = "icon-cube"

  # About section
  [params.about]
    enable = true
    title = "about.title"
    description = ""

    [[params.about.item]]
      name = "Brahim Ait Essaleh"
      position = "Certified guide"
      description = "Born in Zagora. Be ready to enjoy the desert with me."
      img = "images/gallery/gallery_1.jpeg"
      alt = "Brahim"

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "contact.title"
    description = "contact.description"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "B.P.: 349 Zagora Maroc"],
        ["icon-phone", "+212 6 10 83 79 09"],
        ["icon-envelope", "contact@afrique-nature.com"],
        ["icon-globe", '<a href="http://www.afrique-nature.com" target="_blank">www.afrique-nature.com</a>']
      ]

    name = "contact.name"
    email = "contact.email"
    phone = "contact.phone"
    message = "contact.message"
    button = "contact.submit"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Afrique Nature. All Rights Reserved. <br>Created by <a href="https://github.com/lhache/" target="_blank">Louis Hache</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'




DefaultContentLanguage = "en"

[Languages]
[Languages.en]
title = "Afrique Nature"
weight = 1

[Languages.fr]
title = "Afrique Nature"
weight = 2
