# Page settings
baseurl = "localhost:1313"
title = "Elate theme"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Louis Hache"
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "afrique nature"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    gallery = "Gallery"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "afrique nature"
    subtitle = 'Join the family Mamadou for a truly magical experience in the Sahara desert. This family business has seen three generations and can offer a real experience in contrast to some of the commercial alternatives.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
  enable = false

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Our promise to you"
    description = "Professional service, in respect of the humans and the nature"
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Authenticity"
      subtitle = "In all cases you are accompanied by true people of the desert, descendants of the nomad tribes who know the desert like the back of their hands. Rest assured, you will never get lost."

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Ecology"
      subtitle = "The family Mamadou are concerned for the future of the desert and we make sure that we leave it as we find it; you will find us very careful not to harm the environment. Once the excursion is finished, all rubbish is disposed of appropriately. Because we care."

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Local guides"
      subtitle = "You will be accompanied by (depending on the size of your group), a guide, a cook and a camel driver. All people come from the region and know the desert better than their pocket. With them, there is no way you can get lost in the dunes."

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Atmosphere"
      subtitle = "Join us in the ambience and romance of the desert, witness the fire flickering and dancing following the sounds and rhythms of the songs. Singing, speaking, listening, interacting, discovering... Another way of living. When the time comes, either retire to your tent and join the God of dreams or spend the night under the stars."

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Nature"
      subtitle = "You will be surrounded with transcending nature. The Sahara desert is a marvel of our planet. We can't describe you how you will feel, this is something you have to live by yourself to understand why the locals, despite harsh conditions, love this place. "

      [[params.work.row]]
        img = "work_4.jpg"
        alt = "Image4"
        title = "Food"
        subtitle = "Enjoy the hospitality of the family Mamadou. At night, sometimes, you will sit around the fire and you'll taste food lovingly prepared. They taste totally different in the desert! After having sampled lamb tajines, fresh vegetables, Moroccan salad, bread cooked in the sand and of course, the couscous of the Sahara (semolina prepared by hand). It will seem to you that all previous dishes are tasteless in comparison."
  # Work section
  [params.gallery]
    enable = true
    title = "Gallery"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.gallery.row]]
      img = "gallery_1.jpeg"
      alt = "Image2"
    [[params.gallery.row]]
      img = "gallery_2.jpeg"
      alt = "Image2"
    [[params.gallery.row]]
      img = "gallery_3.jpeg"
      alt = "Image3"
    [[params.gallery.row]]
      img = "gallery_6.jpeg"
      alt = "Image6"
    [[params.gallery.row]]
      img = "gallery_7.jpeg"
      alt = "Image7"
    [[params.gallery.row]]
      img = "gallery_8.jpeg"
      alt = "Image8"
    [[params.gallery.row]]
      img = "gallery_9.jpeg"
      alt = "Image9"
    [[params.gallery.row]]
      img = "gallery_10.jpeg"
      alt = "Image10"
    [[params.gallery.row]]
      img = "gallery_11.jpeg"
      alt = "Image11"
    [[params.gallery.row]]
      img = "gallery_12.jpeg"
      alt = "Image12"
    [[params.gallery.row]]
      img = "gallery_13.jpeg"
      alt = "Image13"
    [[params.gallery.row]]
      img = "gallery_17.jpeg"
      alt = "Image14"
    [[params.gallery.row]]
      img = "gallery_15.jpeg"
      alt = "Image15"
    [[params.gallery.row]]
      img = "gallery_16.jpeg"
      alt = "Image16"
    [[params.gallery.row]]
      img = "gallery_14.jpeg"
      alt = "Image17"
    [[params.gallery.row]]
      img = "gallery_18.jpeg"
      alt = "Image18"
    [[params.gallery.row]]
      img = "gallery_20.jpeg"
      alt = "Image20"
    [[params.gallery.row]]
      img = "gallery_22.jpeg"
      alt = "Image22"
    [[params.gallery.row]]
      img = "gallery_21.jpeg"
      alt = "Image21"
    [[params.gallery.row]]
      img = "gallery_24.jpeg"
      alt = "Image24"
    [[params.gallery.row]]
      img = "gallery_25.jpeg"
      alt = "Image25"
    [[params.gallery.row]]
      img = "gallery_19.jpeg"
      alt = "Image19"
    [[params.gallery.row]]
      img = "gallery_5.jpeg"
      alt = "Image5"
    [[params.gallery.row]]
      img = "gallery_26.jpeg"
      alt = "Image26"
    [[params.gallery.row]]
      img = "gallery_27.jpeg"
      alt = "Image27"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "None of them has ever managed to reach Timbuktu but it seems they enjoyed the experience."

    [[params.testimonials.item]]
      quote = "lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies"
      person = 'Louis H.'
      # img = "person1.jpg"
      # alt = "Person1"

    [[params.testimonials.item]]
      quote = "Super mega cool lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies"
      person = 'Louis H.'
      # img = "person2.jpg"
      # alt = "Person2"

    [[params.testimonials.item]]
      quote = "lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies lorem ipsum oospies"
      person = 'Louis H.'
      # img = "person3.jpg"
      # alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "You can choose to cover the desert by foot (trekking), on the back of a dromedary (domestic from Africa) or by 4x4. You can travel on your own, as a couple, as a family or with friends or colleagues, whatever you wish. The family Mamadou can create your own program; your wish is our desire."

    [[params.services.item]]
      title = "Adapted"
      description = "Tours adapted to your physical capabilities, answering to your needs. We await your requirements."
      icon = "icon-magic-wand"
    [[params.services.item]]
      title = "Camping"
      description = "Camping in the heart of the dune Lemraire (10km after the door of the desert), Chegaga (The mother of the sand)."
      icon = "icon-bed"
    [[params.services.item]]
      title = "Comfort"
      description = "Comfortable beds, toilets, showers and a hammam (Turkish bath) facilities at Chegaga."
      icon = "icon-fire"
    [[params.services.item]]
      title = "Care"
      description = "Attentive staff always available to ensure your perfect holiday experience."
      icon = "icon-eye"
    [[params.services.item]]
      title = "Entertainment"
      description = "Entertainment and catering on site: local dishes, jokes, music."
      icon = "icon-video2"
    [[params.services.item]]
      title = "Local"
      description = "Authentic tents, traditional clothing, music from Berbers, Nomads and Harratines (3 tribes from the Drâa valley), a choice of meals to fulfill your dietary requirements. It's up to you."
      icon = "icon-like"


  # Services section
  [params.passion]
    enable = true
    title = "If you are passionate about..."
    description = "The desert offer many wonders. Just adventure and capture them."

    [[params.passion.item]]
      title = "Photography"
      description = "The desert opens its arms to you. Don't miss the magnificent sunrises and sunsets, the incredible dunes, the beautiful trees and shrubs and of course, the brilliance of the nights with a full moon. It is worth having all these simple and magical moments you experience, as part of your personal collection, to give you another vision of the world."
      icon = "icon-camera"
    [[params.passion.item]]
      title = "Astronomy"
      description = "The nights of the desert offer all the opportunities for those who are passionate about the stars. Once comfortably settled in a dune, you can study without light pollution, the sky and its constellations. The desert is truly another planet."
      icon = "icon-star"
    [[params.passion.item]]
      title = "Geology"
      description = "Spend a day to search for those fossils either by foot, a short distance from our camp or by 4x4 to the crystal mountains. Our guides will lead you to the best places for beautiful discoveries (ancient rock drawings, meet rare birds and wild animals in the nature)."
      icon = "icon-cube"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "Afrique Nature - Brahim Ait Essaleh"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "B.P.: 349 Zagora Maroc"],
        ["icon-phone", "+212 6 10 83 79 09"],
        ["icon-envelope", "contact@afrique-nature.com"],
        ["icon-globe", '<a href="http://www.afrique-nature.com" target="_blank">www.afrique-nature.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Afrique Nature. All Rights Reserved. <br>Created by <a href="https://github.com/lhache/" target="_blank">Louis Hache</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'











DefaultContentLanguage = "en"

[Languages]
[Languages.en]
title = "The Better Play"
weight = 1

[Languages.de]
title = "The Better Play"
weight = 2
